development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development_jgw_core
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_jgw_core
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production_jgw_core
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock


<%
env_prefix = case Rails.env
when 'production'
  'production'
when 'test'
  'test'
else
  'development'
end
%>

dev_jgw_gw:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= env_prefix %>_jgw_gw
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock

gwsub:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= env_prefix %>_jgw_gw_pref
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock
